Repository carpenstreet/blender, pull requests merged in 2022-08, with the labels that each got.

#98 [0.2.4 QA] 선택된 object가 없을 시에도, material list가 노출됨
  release/scripts/startup/abler/face_control.py
Labels: bug

#100 [0.2.4 QA] [Use State, Group Navigation] 들여쓰기 구현
  release/scripts/startup/abler/object_control.py
Labels: bug

#115 .blend 파일을 열어도 바로 Tutorial 스플래시가 나올 수 있도록 수정함
  release/scripts/startup/abler/credential_modal.py
Labels: bug

#116 password를 입력했을 때 해당 내용이 그대로 undo history에 노출 되는 현상
  source/blender/editors/interface/interface_handlers.c
Labels: bug

#119 import시 File dialog에서 빈 곳을 클릭하면 뜨는 버그를 resolve
  release/scripts/startup/abler/general.py
  release/scripts/startup/abler/import_external_files.py
  release/scripts/startup/abler/lib/import_file.py
Labels: bug

#124 Zoom to Mouse Position Default값 True로 변경
  release/datafiles/userdef/userdef_default.c
  release/scripts/startup/abler/pref.py
Labels: enhancement

#129 PR 템플릿을 사용할 수 있도록 수정함
  .github/pull_request_template.md
Labels: documentation

#131 레이어 이름 변경 시, 앱이 강제종료되는 현상 수정
  source/blender/editors/interface/interface_handlers.c
Labels: bug
