Repository carpenstreet/blender, pull requests merged in 2022-11, with the labels that each got.

#203 실시간으로 변하는 프로그레스 바 팝업 구현
  release/scripts/startup/abler/export_tab/export_control.py
  release/scripts/startup/abler/export_tab/render_control.py
  source/blender/editors/include/UI_interface.h
  source/blender/editors/interface/interface_templates.c
  source/blender/editors/space_view3d/space_view3d.c
  source/blender/makesrna/intern/rna_ui_api.c
  source/blender/makesrna/intern/rna_wm_api.c
  source/blender/windowmanager/intern/wm_operators.c
  source/blender/windowmanager/intern/wm_splash_screen.c
  source/blender/windowmanager/wm.h
Labels: enhancement

#198 UI 이름 사양서과 싱크 맞추기
  release/scripts/modules/bl_i18n_utils/settings.py
  release/scripts/startup/abler/camera_tab/background_control.py
  release/scripts/startup/abler/camera_tab/camera_control.py
  release/scripts/startup/abler/custom_properties.py
  release/scripts/startup/abler/general_tab/general.py
  release/scripts/startup/abler/scene_tab/layer_control.py
  release/scripts/startup/abler/scene_tab/object_control.py
  release/scripts/startup/abler/scene_tab/scene_control.py
  release/scripts/startup/abler/style_tab/styles_control.py
  source/blender/editors/interface/interface_eyedropper_datablock.c
  source/blender/editors/interface/interface_template_list.cc
  source/blender/editors/interface/interface_templates.c
  source/blender/editors/space_view3d/view3d_edit.c
  source/blender/makesrna/intern/rna_camera.c
  source/blender/makesrna/intern/rna_material.c
  source/blender/makesrna/intern/rna_nodetree.c
  source/blender/makesrna/intern/rna_object.c
  source/blender/makesrna/intern/rna_scene.c
  source/blender/makesrna/intern/rna_userdef.c
Labels: 핵심 경험 개선

#204 skp import를 믹스패널에 추가하고, 몇가지 TODO도 추가함.
  release/scripts/startup/abler/general_tab/general.py
  release/scripts/startup/abler/lib/import_file.py
  release/scripts/startup/abler/lib/tracker/_tracker.py
Labels: 핵심 경험 개선

#192 export 탭 UI 정리 및 리팩토링
  release/scripts/startup/abler/__init__.py
  release/scripts/startup/abler/custom_properties.py
  release/scripts/startup/abler/export_tab/export_control.py
  release/scripts/startup/abler/export_tab/render_control.py
  release/scripts/startup/abler/lib/tracker/_tracker.py
  release/scripts/startup/abler/warning_modal.py
  source/blender/editors/include/UI_interface.h
  source/blender/editors/interface/interface_templates.c
  source/blender/editors/space_view3d/space_view3d.c
  source/blender/makesrna/intern/rna_ui_api.c
  source/blender/makesrna/intern/rna_wm_api.c
  source/blender/windowmanager/intern/wm_operators.c
  source/blender/windowmanager/intern/wm_splash_screen.c
  source/blender/windowmanager/wm.h
Labels: 핵심 경험 개선

#205 Active object가 없을 때 재질 속성에 접근하는 문제
  release/scripts/startup/abler/lib/materials/materials_handler.py
Labels: 핵심 경험 개선

#214 skp와 fbx import 애드온 항상 켜주는 내용 추가
  release/scripts/startup/abler/general_tab/general.py
  release/scripts/startup/abler/lib/import_file.py
Labels: 핵심 경험 개선

#220 Sunlight, Bloom 토글 해제 시 패널 닫히지 않는 문제
  release/scripts/startup/abler/custom_properties.py
  release/scripts/startup/abler/lib/bloom.py
  release/scripts/startup/abler/style_tab/styles_control.py
Labels: QA Issue

#222 Object Control 그리드가 노출되지 않는 문제
  release/scripts/startup/abler/pref.py
Labels: QA Issue

#225 씬 추가 생성 후 삭제 시 에러
  release/scripts/startup/abler/scene_tab/scene_control.py
Labels: QA Issue

#229 파일 뷰어의 display mode 차이나는 에러
  release/scripts/startup/abler/camera_tab/background_control.py
  release/scripts/startup/abler/general_tab/general.py
  release/scripts/startup/abler/lib/import_file.py
Labels: QA Issue

#232 Scene 생성 시 씬이름이 자동으로 내림차순으로 정렬되지 않음
  release/scripts/startup/abler/export_tab/export_control.py
  release/scripts/startup/abler/scene_tab/scene_control.py
Labels: QA Issue

#231 스닙랜더가 작동하지 않는 오류
  release/scripts/startup/abler/export_tab/render_control.py
Labels: 핵심 경험 개선, QA Issue

#233 Save Copy 초기 Filter, Toggle region 에러
  release/scripts/startup/abler/general_tab/general.py
  release/scripts/startup/abler/lib/tracker/_tracker.py
  release/scripts/startup/bl_ui/space_topbar.py
Labels: QA Issue

#234 Object Properties에서 Shadow 토글 설정이 파일에 저장되지 않는 문제
  release/scripts/startup/abler/lib/materials/materials_handler.py
Labels: 핵심 경험 개선

#235 기획서랑 UI 차이나는 문제
  release/scripts/startup/abler/camera_tab/background_control.py
  release/scripts/startup/abler/camera_tab/camera_control.py
  release/scripts/startup/abler/style_tab/styles_control.py
Labels: QA Issue

#238 씬 추가 생성 후 삭제 시 에러 변경사항
  release/scripts/startup/abler/scene_tab/scene_control.py
Labels: QA Issue

#240 Snap 기능 비활성화
  release/scripts/startup/abler/lib/scenes.py
Labels: 핵심 경험 개선

#241 파일 뷰어에서 빈 곳에 더블클릭시 에러
  release/scripts/presets/keyconfig/keymap_data/abler_default.py
Labels: QA Issue

#242 상관없는 프로세스들의 오류에서도 로그인이 안되는 현상이 있어서 이를 고침
  release/scripts/startup/abler/lib/login.py
Labels: bug, QA Issue

#244 파일 뷰어 Filter option Enable 되는 에러
  release/scripts/startup/abler/export_tab/render_control.py
  release/scripts/startup/abler/general_tab/general.py
  release/scripts/startup/abler/lib/import_file.py
Labels: QA Issue

#247 파일 브라우저의 옵션이 변경 안되는 문제
  release/scripts/startup/abler/export_tab/render_control.py
  release/scripts/startup/abler/lib/import_file.py
Labels: QA Issue

#243 여러 에이블러 클라이언트 실행 중에 로그아웃을 해도 아무 반응이 없음
  release/scripts/startup/abler/operators.py
Labels: QA Issue

#248 프로그레스 템플릿 UI 조정
  release/scripts/startup/abler/export_tab/export_control.py
  release/scripts/startup/abler/general_tab/general.py
  release/scripts/startup/abler/lib/string_helper.py
  source/blender/editors/interface/interface_templates.c
Labels: enhancement

#249 .tar 파일 취약점 보완 (@TrellixVulnTeam)
  build_files/buildbot/codesign/base_code_signer.py
Labels: enhancement

#250 에이블러 실행할 때의 애드온 관리
  release/scripts/startup/abler/lib/addons.py
  release/scripts/startup/abler/pref.py
Labels: 핵심 경험 개선

#251 씬 추가 생성 후 지우려고 할 시 뜨는 에러 재처리
  release/scripts/startup/abler/scene_tab/scene_control.py
Labels: QA Issue

#246 Quick Render Viewport 클릭 시 브라우저 이름이 ABLER File View인 문제
  release/scripts/startup/abler/export_tab/render_control.py
Labels: QA Issue

#252 Scene 탭과 Style탭의 순서가 바뀐 에러
  release/scripts/startup/abler/camera_tab/background_control.py
  release/scripts/startup/abler/camera_tab/camera_control.py
  release/scripts/startup/abler/export_tab/export_control.py
  release/scripts/startup/abler/general_tab/general.py
  release/scripts/startup/abler/scene_tab/layer_control.py
  release/scripts/startup/abler/scene_tab/object_control.py
  release/scripts/startup/abler/scene_tab/scene_control.py
  release/scripts/startup/abler/style_tab/styles_control.py
Labels: QA Issue

#257 믹스패널 테스트용 아규먼트 추가
  release/scripts/startup/abler/lib/tracker/_tracker.py
Labels: 핵심 경험 개선

#260 북마크에 없는 디렉터리의 북마크 기능 사용을 제한
  source/blender/editors/space_file/file_ops.c
Labels: QA Issue

#262 씬 삭제 후 포커스된 씬이 없어져서 씬 삭제 시 오류가 발생하는 문제
  release/scripts/startup/abler/scene_tab/scene_control.py
Labels: QA Issue

#264 login auto가 파일 열때마다 실행되는 문제
  release/scripts/startup/abler/startup_flow.py
Labels: QA Issue
