Repository carpenstreet/blender, pull requests merged in 2022-10, with the labels that each got.

#173 에이블러 업데이트 팝업 결과에 따라 에이블러 멈추는 문제 수정
  release/scripts/startup/abler/startup_flow.py
Labels: QA Issue

#141 selected object가 있을 시에, 축 + 대지가 보이도록 하는 기능을 추가함.
  release/datafiles/userdef/userdef_default_theme.c
  release/scripts/startup/abler/pref.py
Labels: 핵심 경험 개선

#137 씬 전환시 EDIT_MODE에서 런타임에러 발생하는 문제
  release/scripts/startup/abler/lib/scenes.py
Labels: 유지보수

#174 오브젝트 면을 기준으로 스냅 기능 활성 및 헤더에서 사용되지 않는 기능 삭제
  release/scripts/startup/abler/lib/scenes.py
  release/scripts/startup/abler/pref.py
  release/scripts/startup/bl_ui/space_view3d.py
Labels: 핵심 경험 개선

#180 Scene 변경 시 Scene 마다 l_exclude 갯수가 다를 때 발생하는 에러
  release/scripts/startup/abler/lib/layers.py
Labels: bug

#172 툴바를 기본으로 표시하고 사용하지 않는 기능 정리하기
  release/scripts/presets/keyconfig/keymap_data/abler_default.py
  release/scripts/startup/abler/general_tab/general.py
  release/scripts/startup/abler/pref.py
  release/scripts/startup/bl_ui/space_toolsystem_toolbar.py
Labels: 핵심 경험 개선

#185 Screen에 ACON3D가 있을때만 내부 area 탐색하기
  release/scripts/startup/abler/pref.py
Labels: bug

#188 Infinity Zoom 모드 활성
  release/scripts/startup/abler/pref.py
Labels: 핵심 경험 개선

#184 Shadow / Shading 한꺼번에 on/off 하는 속성 추가
  release/scripts/startup/abler/custom_properties.py
  release/scripts/startup/abler/lib/shadow.py
  release/scripts/startup/abler/style_tab/styles_control.py
Labels: 핵심 경험 개선

#187 개선된 Scene UI에서 항목 더블클릭으로 씬 이름 변경
  release/scripts/startup/abler/custom_properties.py
  release/scripts/startup/abler/lib/scenes.py
  release/scripts/startup/abler/scene_tab/scene_control.py
Labels: bug, 핵심 경험 개선

#190 View_Camera 가 선택 가능한 에러
  release/scripts/startup/abler/lib/cameras.py
  release/scripts/startup/abler/lib/scenes.py
Labels: bug

#189 Feature/group navigation single layer
  release/scripts/startup/abler/custom_properties.py
  release/scripts/startup/abler/lib/layers.py
  release/scripts/startup/abler/lib/render.py
Labels: enhancement

#194 edge를 line으로 수정
  release/scripts/startup/abler/custom_properties.py
Labels: 핵심 경험 개선

#193 에이블러 메뉴 내 에이블러 미필요 기능 비활성화
  release/scripts/startup/abler/general_tab/general.py
  release/scripts/startup/abler/lib/addons.py
  release/scripts/startup/abler/lib/locales.py
  release/scripts/startup/abler/pref.py
  release/scripts/startup/bl_operators/wm.py
  release/scripts/startup/bl_ui/space_topbar.py
Labels: 핵심 경험 개선

#197 같은 .blend 파일을 Import 실패했을 때 믹스패널 로그가 찍히지 않던 문제 수정
  release/scripts/startup/abler/lib/tracker/_tracker.py
Labels: bug
